# For more details on the format and content:
# https://github.com/robocorp/rcc/blob/master/docs/recipes.md#what-is-in-condayaml
# Tip: Adding a link to the release notes of the packages helps maintenance and security.

channels:
  - conda-forge

dependencies:
  - python=3.9.16                   # https://pyreadiness.org/3.9/
  - pip=22.1.2                      # https://pip.pypa.io/en/stable/news/
  - pip:
      - rpaframework==23.3.0                  # https://rpaframework.org/releasenotes.html
      - rpaframework-assistant==2.3.0         # https://rpaframework.org/releasenotes.html
      - openai==0.27.8                        # https://pypi.org/project/openai/
      - robocorp-tasks==1.0.0                 # https://pypi.org/project/robocorp-tasks/
      - robocorp-vault==0.4.0                 # https://pypi.org/project/robocorp-vault/